<div class="row-fluid">
	<h1 class="text-center">Administraci&oacute;n de Contenidos</h1><hr><br>
	<div class="col-md-8 col-md-offset-2">
		<!--botón que abre una modal para añadir un nuevo post-->
		<a href="contenido/new" class="btn btn-success add pull-right">Nueva noticia</a><br><hr>
		<table class="table table-striped table-bordered table-condensed text-center">
			<thead>
				<tr>
					<th class="text-center">No</th>
		            <th class="text-center">Título</th>
		            <th class="text-center">Contenido</th>
		            <th class="text-center">Categoria</th>
		            <th class="text-center">Fecha de creación</th>
		            <th class="text-center">Fecha de modificación</th>
		            <th class="text-center">
									<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Editar									
								</th>
		            <th class="text-center">
										<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Eliminar
								</th>
		        </tr>
			</thead>
			<tbody>
<?php

$contenidos = Contenidos::find();
$contador = 0;

foreach ($contenidos as  $contenido)
{
	$contador++;
	echo "<tr>";
	echo "<td>".($contador)."</td>";
	echo "<td>".$contenido->titulo."</td>";
	echo "<td>".substr($contenido->cuerpo,0,50)."</td>";
	echo "<td>".$contenido->categorias->nombre."</td>";
	echo "<td>".$contenido->created."</td>";
	echo "<td>".$contenido->modified."</td>";

	echo "<td>".
						$this->tag->linkTo(array(	"contenido/update?id=".$contenido->id,"Editar","class"=>"btn btn-warning")).
						"</td>";
	echo "<td>".
						$this->tag->linkTo(array(	"contenido/delete?id=".$contenido->id,"Eliminar","class"=>"btn btn-danger")).
						"</td>";


	echo "</tr>";
}
echo "</tbody>";
echo "</table>";
echo "</div>";
echo "</div>";
?>
